name: 'Get branch name'
description: 'Export branch name as environment variable'
branding:
  icon: 'git-branch'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [ "${GITHUB_HEAD_REF}" != '' ]; then
          echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV;
          echo "PR detected: branch name ${GITHUB_HEAD_REF}";
        else
          echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV;
          echo "Normal push detected: branch name ${GITHUB_REF_NAME}";
        fi
